<a href="https://colab.research.google.com/github/abhinavreddyjitta/ML_LAB_2026-27/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array1 = np.array([1,2,3,4,5])
print(array1)

[1 2 3 4 5]


In [2]:
import numpy as np
array2 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [4]:
import numpy as np
array3 = np.array([
    [
        [1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8],
        [9, 10, 11, 12, 13]
    ],
    [
        [5, 6, 7, 8, 9],
        [10, 11, 12, 13,14],
        [15, 16, 17, 18, 19]
    ]
])
print(array3)

[[[ 1  2  3  4  5]
  [ 4  5  6  7  8]
  [ 9 10 11 12 13]]

 [[ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [5]:
array1 = np.array([2, 4, 6])
print(array1.dtype)

int64


In [6]:
print(array1.ndim)

1


In [7]:
print(array1.size)

3


In [8]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])
print(array1.shape)


(2, 3)


In [9]:
array1 = np.array([6, 7, 8, 10, 13])
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)
print(array1.itemsize)
print(array2.itemsize)

8
4


In [10]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7a0aa6daad40>
Data of array2 is:  <memory at 0x7a0aa57f0a00>


In [11]:
array1 = np.array([1, 3, 5, 7, 9])
print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


In [12]:
array1[1]=10
print(array1)

[ 1 10  5  7  9]


In [13]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])
element1 = array1[1, 3]
print("4th Element at 2nd Row:",element1)
element2 = array1[0, 1]
print("2nd Element at First Row:",element2)


4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [14]:
array1 = np.array([1, 2, 3, 4, 5])
median = np.median(array1)

print(median)


3.0


In [15]:
marks = np.array([76, 78, 81, 66, 85])
mean_marks = np.mean(marks)
print(mean_marks)

77.2


In [16]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.std(marks)
print(std_marks)

6.368673331236263


In [17]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.percentile(marks,50)
print(std_marks)

78.0


In [18]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.min(marks)
print(std_marks)

66


In [19]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.max(marks)
print(std_marks)

85


In [20]:
import numpy as np
x = np.array([[1, 2, 3], [3, 4, 5]])
y = np.array([6,7,8])
z = np.add(x,y)
print("Addition of x and y:\n", z)
z = np.subtract(x,y)
print("Subtraction of y from x:\n", z)
z = np.multiply(x,y)
print("Element-wise multiplication of x and y:\n", z)

Addition of x and y:
 [[ 7  9 11]
 [ 9 11 13]]
Subtraction of y from x:
 [[-5 -5 -5]
 [-3 -3 -3]]
Element-wise multiplication of x and y:
 [[ 6 14 24]
 [18 28 40]]


In [21]:
import numpy as np

my_array = np.array([1,2,3,4])
print("my_array before appending:", my_array)
new_array = np.append(my_array, [7, 8, 9, 10])
print("new_array:", new_array)
print("my_array after appending:", my_array)

my_array before appending: [1 2 3 4]
new_array: [ 1  2  3  4  7  8  9 10]
my_array after appending: [1 2 3 4]


In [22]:
import numpy as np

my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print("my_2d_array before appending:\n", my_2d_array)
new_2d_array = np.append(my_2d_array, [[7], [8]], axis=1)
print("new_2d_array:\n", new_2d_array)
print("my_2d_array after appending:\n", my_2d_array)

my_2d_array before appending:
 [[1 2 3 4]
 [5 6 7 8]]
new_2d_array:
 [[1 2 3 4 7]
 [5 6 7 8 8]]
my_2d_array after appending:
 [[1 2 3 4]
 [5 6 7 8]]


In [23]:
import numpy as np
my_array = np.array([1,2,3,4])
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
np.insert(my_array, 1, 5)
np.delete(my_array,[1])

array([1, 3, 4])